### ISSUE TITLE
mypy segmentation fault due to udf

### ISSUE THREAD

**Issue by chehsunliu** [zero323/pyspark-stubs#261] opened 2019-10-04 08:11 UTC
I encountered this issue when tried to upgrade from `2.4.0.post5` to `2.4.0.post6`. Here are the steps to reproduce the error:

```sh
$ python --version
Python 3.7.3
$ python -m venv venv
$ source ./venv/bin/activate
(venv) $ pip install pyspark==2.4.3 pyspark-stubs==2.4.0.post6 mypy==0.720
(venv) $ echo "from pyspark.sql.functions import udf" > a.py
(venv) $ mypy -v .
LOG:  Could not load plugins snapshot: @plugins_snapshot.json

LOG:  Mypy Version:           0.720
LOG:  Config File:            Default
LOG:  Configured Executable:  /tmp/pysp/venv/bin/python
LOG:  Current Executable:     /tmp/pysp/venv/bin/python
.
.
.
LOG:  Writing pyspark.sql /tmp/pysp/venv/lib/python3.7/site-packages/pyspark/sql/__init__.pyi pyspark/sql/__init__.meta.json pyspark/sql/__init__.data.json
LOG:  Cached module pyspark.sql has changed interface
LOG:  Writing pyspark /tmp/pysp/venv/lib/python3.7/site-packages/pyspark/__init__.pyi pyspark/__init__.meta.json pyspark/__init__.data.json
LOG:  Cached module pyspark has changed interface
LOG:  Processing SCC singleton (pyspark.sql.functions) as inherently stale with stale deps (builtins pyspark.sql._typing pyspark.sql.column pyspark.sql.dataframe pyspark.sql.types typing)
[1]    21994 segmentation fault (core dumped)  mypy -v .
```

The error will disappear if the following lines are removed:

https://github.com/zero323/pyspark-stubs/blob/a85230ee1d8f70d5d0a14ff5b3b84cccd848e942/third_party/3/pyspark/sql/functions.pyi#L244-L245

**Comment by zero323** [comment] 2019-10-04 09:03
Thank you for your detailed report @chehsunliu, however this is a duplicate of #245. 

In general, I consider this wontifx issue - the annotation is valid, and reflect latest state of the ecosystem, and since I don't assume that users choose any specific type checker (you can check my response [here](https://github.com/conda-forge/staged-recipes/pull/9480#discussion_r322842937) for details), the obvious "fix", which is pinning this version  to specific Mypy release, is no go. Maybe we could yield some installation warning if lower MyPy is detected, but I am not sure it will make any difference.

**Closed by zero323** 2019-10-04 09:03 UTC
