### ISSUE TITLE
DataFrameLike does not have to_sql method

### ISSUE THREAD

**Issue by consciousgaze** [zero323/pyspark-stubs#553] opened 2021-09-12 21:36 UTC
The [DataFrameLike](https://github.com/zero323/pyspark-stubs/blob/5369338cabcef5f4eb475f037614f4bd4e9e2f39/third_party/3/pyspark/sql/pandas/_typing/protocols/frame.pyi#L19) class needs to have to_sql method. Otherwise an unnecessary type conversion will be required after toPandas to use to_sql.

**Comment by zero323** [comment] 2021-10-08 15:50
Thanks for reporting @consciousgaze.

There are probably other missing methods in this `Protocol` (it was intended as a workaround until Pandas exposes their own annotations). Do you want to create PR to fix this?

**Comment by zero323** [comment] 2022-01-07 02:28
I am closing this with wontfix, because there is no reasonable way of resolving this without causing version to version inconsistencies with usptream Spark annotations.

If you experience this problem I recommend explicit casting as described in[SPARK-34544](https://issues.apache.org/jira/browse/SPARK-34544) (alternatively to `Any` one can use pandas-stubs and cast to actual Pandas type).

**Closed as completed by zero323** 2022-01-07 02:28 UTC
Labels: wontfix
